
import {
  ChevronLeft,
  ChevronRight,
  CircleUser,
  Clock,
  FileText,
  Home,
  Inbox,
  List,
  LogOut,
  Menu,
  Moon,
  Plus,
  Search,
  Sidebar as SidebarIcon,
  Sun,
  User,
  Users,
  X,
  Calendar,
  BarChart3,
  Settings,
  CheckCircle2,
  AlertTriangle,
  LayoutDashboard,
  ClipboardList,
  Tags,
  Filter,
  Loader2,
  Bell,
  Building2,
  Lock,
  PenSquare,
  Eye,
  ArrowUpDown,
  Download,
  UserPlus,
  Trash,
} from "lucide-react";

export const Icons = {
  logo: FileText,
  menu: Menu,
  close: X,
  user: User,
  home: Home,
  tasks: List,
  inbox: Inbox,
  profile: CircleUser,
  logout: LogOut,
  sun: Sun,
  moon: Moon,
  sidebar: SidebarIcon,
  add: Plus,
  calendar: Calendar,
  search: Search,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  clock: Clock,
  chart: BarChart3,
  settings: Settings,
  completed: CheckCircle2,
  warning: AlertTriangle,
  dashboard: LayoutDashboard,
  todos: ClipboardList,
  users: Users,
  tag: Tags,
  filter: Filter,
  spinner: Loader2,
  notification: Bell,
  building: Building2,
  lock: Lock,
  edit: PenSquare,
  view: Eye,
  bell: Bell,
  sort: ArrowUpDown,
  fileText: FileText,
  download: Download,
  userPlus: UserPlus,
  trash: Trash,
};
