
import {
  ChevronLeft,
  ChevronRight,
  CircleUser,
  Clock,
  FileText,
  Home,
  Inbox,
  List,
  LogOut,
  Menu,
  Moon,
  Plus,
  Search,
  Sidebar as SidebarIcon,
  Sun,
  User,
  Users,
  X,
  Calendar,
  BarChart3,
  Settings,
  CheckCircle2,
  AlertTriangle,
  LayoutDashboard,
  ClipboardList,
  Tags,
  Filter,
  Loader2,
  Bell,
  Building2,
  Lock,
  PenSquare,
  Eye,
  ArrowUpDown,
  Download,
  UserPlus,
  Trash,
  UserMinus,
  Mail,
  Phone,
  Globe,
  MapPin,
  Shield,
  MessageSquare,
  Building,
  Activity,
} from "lucide-react";

export const Icons = {
  logo: FileText,
  menu: Menu,
  close: X,
  user: User,
  home: Home,
  tasks: List,
  inbox: Inbox,
  profile: CircleUser,
  logout: LogOut,
  sun: Sun,
  moon: Moon,
  sidebar: SidebarIcon,
  add: Plus,
  plus: Plus, // Adding the missing Plus icon
  calendar: Calendar,
  search: Search,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  clock: Clock,
  chart: BarChart3,
  settings: Settings,
  completed: CheckCircle2,
  warning: AlertTriangle,
  dashboard: LayoutDashboard,
  todos: ClipboardList,
  clipboardList: ClipboardList, // Added missing icon
  users: Users,
  tag: Tags,
  filter: Filter,
  spinner: Loader2,
  notification: Bell,
  building: Building,
  building2: Building2, // Adding the missing Building2 icon
  lock: Lock,
  edit: PenSquare,
  view: Eye,
  bell: Bell,
  sort: ArrowUpDown,
  fileText: FileText,
  download: Download,
  userPlus: UserPlus,
  trash: Trash,
  userMinus: UserMinus,
  mail: Mail,
  phone: Phone,
  globe: Globe,
  location: MapPin,
  shield: Shield,
  message: MessageSquare,
  activity: Activity, // Added missing icon
};

