// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://stbmlbszcpsaxwamrqsx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN0Ym1sYnN6Y3BzYXh3YW1ycXN4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ0Mjk0NTYsImV4cCI6MjA2MDAwNTQ1Nn0.8sDi-QJ5T4DzkUiWV_PBO3YcGAG6vtIEXISjRjMUYAA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);